# Generated by Django 4.2.7 on 2026-04-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisingcampaign',
            old_name='service',
            new_name='product',
        ),
    ]
