# Generated by Django 4.2.7 on 2026-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата конверсии')),
            ],
            options={
                'verbose_name': 'Активный клиент',
                'verbose_name_plural': 'Активные клиенты',
            },
        ),
    ]
