# Generated by Django 4.2.7 on 2026-04-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeclient',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contracts.contract', verbose_name='Контракт'),
        ),
    ]
