# Generated by Django 4.2.7 on 2026-04-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeclient',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='leads.lead', verbose_name='Потенциальный клиент'),
        ),
    ]
